"""add user_id to api_tokens

Revision ID: 09d75b0dfde5
Revises: a079c458d58b
Create Date: 2026-06-09 04:07:29.052622

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09d75b0dfde5"
down_revision: str | Sequence[str] | None = "a079c458d58b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add nullable first so existing rows aren't rejected
    op.add_column("api_tokens", sa.Column("user_id", sa.UUID(as_uuid=False), nullable=True))
    # Backfill: assign all orphaned tokens to the first (admin) user
    op.execute(
        "UPDATE api_tokens SET user_id = (SELECT id FROM users ORDER BY created_at LIMIT 1) "
        "WHERE user_id IS NULL"
    )
    # Now enforce NOT NULL and FK
    op.alter_column("api_tokens", "user_id", nullable=False)
    op.create_foreign_key(None, "api_tokens", "users", ["user_id"], ["id"], ondelete="CASCADE")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "api_tokens", type_="foreignkey")
    op.drop_column("api_tokens", "user_id")
    # ### end Alembic commands ###
