"""add_machine_id_to_api_tokens

Revision ID: 1409d10906fb
Revises: 7da1313001d6
Create Date: 2026-06-09 05:44:31.564776

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1409d10906fb"
down_revision: str | Sequence[str] | None = "7da1313001d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_tokens", sa.Column("machine_id", sa.UUID(as_uuid=False), nullable=True))
    op.create_index("ix_api_tokens_machine_id", "api_tokens", ["machine_id"], unique=False)
    op.create_foreign_key(
        None, "api_tokens", "machines", ["machine_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "api_tokens", type_="foreignkey")
    op.drop_index("ix_api_tokens_machine_id", table_name="api_tokens")
    op.drop_column("api_tokens", "machine_id")
    # ### end Alembic commands ###
